import mongoose from "mongoose";

const useregisterschema = mongoose.Schema({
  candidateName:{
    type:String
  },
  candidateEmail:{
    type:String
  },
  candidatePassword:{
    type:String
  },
  role:{
    type:String
  },
  candidatePicture:{
    type:String
  },
  candidateNumber:{
    type:String
  },
  candidateCollege:{
    type:String
  },
  candidateCourse:{
    type:String
  },
  candidateBranch:{
    type:String
  },
  candidateCity:{
    type:String
  },

// ----------- EXPERT --------------

  expertName:{
    type:String
  },
  expertPicture:{
    type:String
  },
  expertOrgEmail:{
    type:String
  },
  expertPassword:{
    type:String
  },
  expertPersonalEmail:{
    type:String
  },
  expertExperience:{
    type:String
  },
  expertProfilePhoto:{
    type:String
  },
  expertPhoneNumber:{
    type:String
  },
  expertGender:{
    type:String
  },
  expertCity:{
    type:String
  },
  expertCountry:{
    type:String
  },
  expertState:{
    type:String
  },
  expertDOB:{
    type:Date
  },
  expertLinkedin:{
    type:String
  },
  expertYoutube:{
    type:String
  },
  expertInstagram:{
    type:String
  },
  expertCurrentCompany:{
    type:String
  },
  expertBio:{
    type:String
  },
  expertAbout:{
    type:String
  },
  expertIndAccountNumber:{
    type:String
  },
  expertIndAccountHolderName:{
    type:String
  },
  expertIndIfscCode:{
    type:String
  },
  expertIndBranchName:{
    type:String
  },
  expertIndUPI:{
    type:String
  },
  expertOUTaccountNumber:{
    type:String
  },
  expertOUTaccountHolderName:{
    type:String
  },
  expertOUTianNumber:{
    type:String
  },
  expertOUTswiftCode:{
    type:String
  },
}) 

const UserRegisterSchema = mongoose.model("userdetails", useregisterschema)
export default UserRegisterSchema;